### ISSUE TITLE
Cosmetic bug: Duplicate "Already synced" messages

### ISSUE THREAD

**Issue by stacksjb** [scottquach/Canvas-Assignments-Transfer-For-Todoist#11]
The response "Assignment Already Synced" is printed twice for assignments already synced/
`Working...
the key was in dict, don't create project
Assignment already synced: Training for Students
assignment already synced
Done!`

Looks to be an issue with the if/else closes in the def transfer_assingments_to_todoist. 

What is the scenario being accounted for with the second "Assignment already synced?"? Shouldn't everything fall into already submitted or already synced?

Probably need to rework the logic with some "else/if" instead of setting the is_synced parameter to false and then starting new logic for it? Or we could add a second variable for is_submitted and then if the second print to only print submitted?

**Comment by scottquach** [comment]
I've removed an extraneous log in one of the else ifs that should alleviate the duplication.
