### ISSUE TITLE
BROKEN AS OF NOV 2022

### ISSUE THREAD

**Issue by stacksjb** [scottquach/Canvas-Assignments-Transfer-For-Todoist#19]
As of Nov 2022, Todoist has shut off the todoist-python (https://github.com/Doist/todoist-python) so this no longer works

They suggest you migrate to https://github.com/Doist/todoist-api-python

I will work on migrating my branch to that.

**Comment by scottquach** [comment]
Thank you for notifying me of this change, I will look to start a migration plan to the new sdk

**Comment by Nassuel** [comment]
Resolved on #20
