### ISSUE TITLE
Delete uneeded files

### ISSUE THREAD

**Issue by stacksjb** [scottquach/Canvas-Assignments-Transfer-For-Todoist#24]
Remove or archive unneeded files
[canvas_to_todoist.py](https://github.com/scottquach/Canvas-Assignments-Transfer-For-Todoist/blob/master/canvas_to_todoist.py)
[config.json](https://github.com/stacksjb/Canvas-Assignments-Transfer-For-Todoist-S/blob/master/config.json) (auto generated on first script run)

**Comment by stacksjb** [comment]
@scottquach please remove files so I can complete merge

**Comment by scottquach** [comment]
These have been removed
