### ISSUE TITLE
Does not display courses past 100

### ISSUE THREAD

**Issue by pennyshi** [scottquach/Canvas-Assignments-Transfer-For-Todoist#37]
The courses displayed is capped at 100 and courses after the 100th are omitted and cannot be selected

**Comment by stacksjb** [comment]
Interesting - are you really enrolled in >100 courses? :) 

Probably same pagination issue needs to be added.

**Comment by pennyshi** [comment]
The list shows all courses I've enrolled or audited on Canvas over five years, so yup more than 100!

**Comment by stacksjb** [comment]
Wow! Never met anyone in the wild with that issue - most schools delete courses after the semester is over, so you don't have all the active ones.

That said, we just need to add pagination, so I'll mark that as a bug and work to fix that at some point. Can't promise any timeframe as I am working on some other rework at the moment though.

**Comment by stacksjb** [comment]
@pennyshi can you try this version? I reused/added the pagination code to the select_courses
your list might be massive, sorry there isn't much I can do about that if your school is keeping everything on Canvas :)
[easy_run.py.zip](https://github.com/scottquach/Canvas-Assignments-Transfer-For-Todoist/files/11346175/easy_run.py.zip)

**Comment by stacksjb** [comment]
If it works, then I can push to the repo, but I have no access to an account with that many courses to test :)

**Comment by stacksjb** [comment]
I figured out a way to test this, I'll see if I can get it working

**Comment by stacksjb** [comment]
Note to self: Test with artificially low return limit

**Comment by stacksjb** [comment]
hi @pennyshi , I was looking at Canvas today and they let you filter by state. Would only returning "active" courses fulfill the need?

(https://community.canvaslms.com/t5/Canvas-Resource-Documents/Canvas-Enrollment-Status-Comparison/ta-p/387055)

**Comment by stacksjb** [comment]
@stacksjb note to self to add filtering to script for only active courses.

**Comment by pennyshi** [comment]
hey so sorry for late reply! for the new zip file you uploaded I ran it and encountered this error 
<img width="885" alt="image" src="https://github.com/scottquach/Canvas-Assignments-Transfer-For-Todoist/assets/48363128/cea64364-1348-4972-b83b-83d37f476034">

**Comment by pennyshi** [comment]
> hi @pennyshi , I was looking at Canvas today and they let you filter by state. Would only returning "active" courses fulfill the need?
> 
> (https://community.canvaslms.com/t5/Canvas-Resource-Documents/Canvas-Enrollment-Status-Comparison/ta-p/387055)

I'm wondering what do you mean by this? (I don't see the option to control this, if you mean within the Canvas interface)

**Comment by stacksjb** [comment]
Go to your Canvas "All Courses" page (https://school.instructure.com/courses)

You should get three sections, with Current, Past, and Future enrollments.

"Active" courses would mean it will only return those in the "Current" section.

**Comment by stacksjb** [comment]
Hello,

I have updated the most recent version to only return courses in an "Active" state. This should resolve that issue for you in the meantime - would you let me know?

If not we can investigate adding iterations, but seems to be a pretty edge use case :)
