### ISSUE TITLE
ToDoist API requests don't send, 410 error.

### ISSUE THREAD

**Issue by stackanthony** [scottquach/Canvas-Assignments-Transfer-For-Todoist#40]
I beleive this is a problem with the API version it's requesting. We may need to replace the calls from  https://api.todoist.com/rest/v1/projects to https://api.todoist.com/rest/v2/projects

**Comment by stackanthony** [comment]
Figured it out, it was due to my Python version being outdated. Believe it was less than 3.6 but > 3

**Comment by stacksjb** [comment]
Thanks! This is working fine for me, closing.
