### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by afroemming** [scottquach/Canvas-Assignments-Transfer-For-Todoist#45]
When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

Even in the absence of a license file, you may grant some rights in cases where you publish your source code to a site that requires accepting terms of service. For example, if you publish your source code in a public repository on GitHub, you have accepted the [Terms of Service](https://help.github.com/articles/github-terms-of-service), by which you allow others to view and fork your repository. Others may not need your permission if [limitations and exceptions to copyright](https://en.wikipedia.org/wiki/Limitations_and_exceptions_to_copyright) apply to their particular situation. Neither site terms nor jurisdiction-specific copyright limitations are sufficient for the kinds of collaboration that people usually seek on a public code host, such as experimentation, modification, and sharing as fostered by an open source license.

See https://choosealicense.com/no-permission/

As each contributor holds copyright for the portions of the program they wrote, their consent would be needed to add a license for that portion, but it could be done piecemeal for each person's contributions.

**Comment by stacksjb** [comment]
@scottquach do you have a preferred license?

I generally go with the MIT License or the GNUGPL (https://choosealicense.com/licenses/ has a good guide) for larger projects (like this), with the Unlicense for smaller code that I don't really care about.

The libraries we rely on (such as todoist-api-python) are licensed under MIT.

**Comment by scottquach** [comment]
Nice catch on the license!

I'm in favor of a MIT License, considering the existing contributions and forks from the open source community. If there are no objections i'll add one to the repo in a day or so.

**Comment by stacksjb** [comment]
Closing as completed
