### ISSUE TITLE
Custom Todoist sub-project target + config

### ISSUE THREAD

**Issue by juliancolb** [scottquach/Canvas-Assignments-Transfer-For-Todoist#51]
Hi guys, cool project! I am wanting to use this script in my school workflow. I have briefly read through the script, and I couldn't seem to find a way to add my classes as a sub-project. I personally like to keep my classes as sub-projects in a "school" project. I think it would be a nice enhancement to allow this functionality and to add a parameter in the config and initialization to mark where to populate canvas assingments.

I am just now starting this semester of classes, so I won't immediately have time to read the API docs and create a PR, but if you guys like this idea I would be happy to contribute.

Also, I am not sure how closely this project is being maintained, but seeing as I would like to use this script and am invested in it's success, I am happy to contribute any necessary code maintenance!

**Comment by stacksjb** [comment]
If you just want the project nested, you can simply run the script as normal, then move the project underneath a parent "school" project (that's what I do). The script doesn't care where it is located, it just looks for one matching by name.

Am I misunderstanding your request, or is it that simple?

**Comment by juliancolb** [comment]
Thank you for your help! You are right, it is that simple. I did not realize that rerunning the script would still work after moving the Todoist projects around.
