### ISSUE TITLE
Unable to handle classes with invalid Todoist characters

### ISSUE THREAD

**Issue by stacksjb** [scottquach/Canvas-Assignments-Transfer-For-Todoist#6]
Todoist Projects don't allow most special characters (see https://todoist.com/help/articles/create-a-project)

> When creating a project, you can’t use  # " ( ) | & ! or , in the project name. The only special characters allowed in project names are . _ and -.

However, I have a canvas class which contains an "&" character in the title, resulting in a KeyError when it attempts to create the associated tasks. It appears the script initially creates the project within todoist (with an underscore _ instead of &), and then each subsequent run simply creates yet another project with the same name within Todoist.

I'm not sure the best way to handle this - it seems the easiest would be to just do a simple  replace and substitute for any of those special characters prior to execution.

**Comment by scottquach** [comment]
Should be able to resolve by standardizing a regex replace in most places. Will get a fix out in the next hour or so

**Comment by scottquach** [comment]
Check the latest master branch commits to see if it works now I've added the following regex substitutions

`courses_id_name_dict[course.get('id', None)] = re.sub(r'[^-a-zA-Z._\s]', '', course.get('name', ''))`

**Comment by stacksjb** [comment]
That is a much better solution than the path I was going down of string substitution.
However it does remove course numbers, would you add 0-9 to the regex?

**Comment by stacksjb** [comment]
Tested and it works, just need to add 0-9 to regex, I'll add that to my latest PR

**Comment by stacksjb** [comment]
Latest PR should resolve this. Let me know once you've had a chance to test and confirm

**Comment by stacksjb** [comment]
One unrelated comment - I only updated the easy_run.py, not any of the others, since I haven't used them - I think it might make sense to archive the other files.

**Comment by scottquach** [comment]
Yes, a few structural cleanups are in order. The retrieve_canvas_course_ids.py may still be useful as a debugging tool though.

**Comment by stacksjb** [comment]
Another question: Is there a particular reason you are storing the API keys in text and reading the lines in as plaintext? Was that just for simplicity in writing them out when they're first entered?

**Comment by scottquach** [comment]
Was mainly a simplicity standpoint for my knowledge at the time. Nowadays tbh it would probably be better to store the information in a .json file instead of a .txt so that properties names can be given for the API keys and the courses can be something of an array instead of newlines.

**Comment by scottquach** [comment]
I can most likely make that simplification within the next day or so. Creating a config.json file that looks something like this instead

`{
	"todoist_api_key": "",
	"canvas_api_key": "",
	"courses": []
}`

**Comment by stacksjb** [comment]
Waiting on latest PR merge to close.

**Comment by stacksjb** [comment]
Agree that a separate config.json makes sense, I was looking at that method as well.

While you're at it, if you would add the API URL (canvas_api_heading) as a variable, that would be good as that is different for custom URLs.

Other variables that would be useful to add at the same time include the task priority (I'd like to create tasks at a higher priority than the default) and task labels.

**Comment by scottquach** [comment]
If you check master easy_run.py has been converted to a .json config file. This also now allows for additional config properties in the future!

**Comment by stacksjb** [comment]
Thx, I have pulled it and made some changes, check latest PR.
